# Generated by Django 4.1 on 2022-12-13 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('typeoperation', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('datecreate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'ordering': ['datecreate'],
            },
        ),
    ]
