# Generated by Django 4.1 on 2022-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='typeoperation',
            field=models.CharField(choices=[('P', 'Prohibited'), ('E', 'Exit')], max_length=1),
        ),
    ]
