# Generated by Django 4.1 on 2022-12-13 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balancecontrol', '0002_alter_balance_typeoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='datecreate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
