# Generated by Django 4.1 on 2022-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancecontrol', '0004_alter_balance_options_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
