# Generated by Django 4.1 on 2022-12-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancecontrol', '0005_balance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
